#!/usr/bin/env node
/**
 * readme-gen.mjs
 * ES Module version of the README generator with tree structure.
 * Local-first, no external dependencies, privacy-focused.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import readline from 'node:readline';

// Get the directory name of the current module
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration
const IGNORE_DIRS = ['node_modules', '.git', '.patches', 'dist', 'build', 'coverage'];
const OUTPUT_FILE = 'README.md';
const WRAPPER_SCRIPT_NAME = 'readme-gen';
const TARGET_DIR = path.join(process.env.HOME || process.env.USERPROFILE || '.', 'bin');
const CLITools_PATH = path.join(process.env.HOME || process.env.USERPROFILE || '.', 'git/clitools/node/readme-gen/index.js');

// Helper to prompt user
function promptUser(question) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim().toLowerCase());
    });
  });
}

// Recursive function to build tree structure showing ALL files (including hidden)
function buildTree(dirPath, prefix = '', isLast = true) {
  let result = '';
  
  // Read all entries, including hidden ones
  const entries = fs.readdirSync(dirPath, { withFileTypes: true })
    .filter(entry => {
      // Keep the ignore list for system folders (node_modules, .git, etc.)
      if (IGNORE_DIRS.includes(entry.name)) return false;
      
      // REMOVE THE HIDDEN FILE FILTER HERE
      // Previously: if (entry.name.startsWith('.') && ...) return false;
      // Now: We allow all entries except those in IGNORE_DIRS
      
      return true;
    })
    .sort((a, b) => a.name.localeCompare(b.name));

  const total = entries.length;

  for (let i = 0; i < total; i++) {
    const entry = entries[i];
    const isLastEntry = i === total - 1;
    
    const connector = isLastEntry ? '└── ' : '├── ';
    const nextPrefix = prefix + (isLastEntry ? '    ' : '│   ');
    
    result += prefix + connector + entry.name + '\n';

    if (entry.isDirectory()) {
      result += buildTree(path.join(dirPath, entry.name), nextPrefix, isLastEntry);
    }
  }

  return result;
}

async function setupWrapper() {
  const targetPath = path.join(TARGET_DIR, WRAPPER_SCRIPT_NAME);
  
  if (!fs.existsSync(TARGET_DIR)) {
    fs.mkdirSync(TARGET_DIR, { recursive: true });
    console.log(`Created directory: ${TARGET_DIR}`);
  }

  const wrapperContent = `#!/bin/bash
exec node "${CLITools_PATH}" "$@"
`;

  try {
    fs.writeFileSync(targetPath, wrapperContent);
    console.log(`Wrapper script created at: ${targetPath}`);
    console.log(`Please run: chmod +x "${targetPath}"`);
    console.log(`Ensure the path in the script (${CLITools_PATH}) points to your actual installation.`);
  } catch (err) {
    console.error(`Failed to create wrapper script: ${err.message}`);
    process.exit(1);
  }
}

async function generateReadme() {
  const rootDir = process.cwd();
  
  // 1. Check if README exists
  const outputPath = path.join(rootDir, OUTPUT_FILE);
  if (fs.existsSync(outputPath)) {
    const answer = await promptUser(`README.md already exists. Overwrite? (y/n): `);
    if (answer !== 'y') {
      console.log('Operation cancelled.');
      process.exit(0);
    }
  }

  // 2. Scan for package.json
  const pkgPath = path.join(rootDir, 'package.json');
  let pkgData = {};
  let hasPackageJson = false;

  if (fs.existsSync(pkgPath)) {
    try {
      const rawContent = fs.readFileSync(pkgPath, 'utf8');
      pkgData = JSON.parse(rawContent);
      hasPackageJson = true;
    } catch (e) {
      console.warn('Warning: Could not parse package.json. Proceeding with defaults.');
    }
  }

  const mainEntry = pkgData.main || 'index.js';
  const description = pkgData.description || 'A project generated by readme-gen.';
  const name = pkgData.name || path.basename(rootDir);
  const version = pkgData.version || '0.0.0';
  const license = pkgData.license || 'MIT';
  
  const deps = pkgData.dependencies || {};
  const devDeps = pkgData.devDependencies || {};
  
  // 3. Build Tree Structure
  const treeOutput = buildTree(rootDir);

  // 4. Build the Markdown Content
  let md = `# ${name}\n\n`;
  md += `> ${description}\n\n`;
  md += `**Version:** ${version} | **Main Entry:** \`${mainEntry}\` | **License:** ${license}\n\n`;
  
  md += `## Installation\n\n`;
  md += '```bash\n';
  md += 'npm install\n';
  md += '```\n\n';

  md += `## Dependencies\n\n`;
  if (Object.keys(deps).length > 0) {
    md += '### Production\n';
    Object.keys(deps).forEach(dep => md += `- [${dep}](https://www.npmjs.com/package/${dep})\n`);
    md += '\n';
  }
  
  if (Object.keys(devDeps).length > 0) {
    md += '### Development\n';
    Object.keys(devDeps).forEach(dep => md += `- [${dep}](https://www.npmjs.com/package/${dep})\n`);
    md += '\n';
  }

  md += `## Project Structure\n\n`;
  md += '```text\n';
  md += treeOutput;
  md += '```\n\n';

  md += `## Usage\n\n`;
  md += `<!-- TODO: Replace this placeholder with specific usage instructions. -->\n`;
  md += `This project is a template. Update this section with:\n`;
  md += `1. How to run the application.\n`;
  md += `2. Configuration requirements.\n`;
  md += `3. Example commands.\n\n`;
  
  md += '```javascript\n';
  md += '// Example import\n';
  md += `const ${name.replace(/-/g, '_')} = require('./${mainEntry.replace('.js', '')}');\n`;
  md += '```\n\n';

  md += `## Contributing\n\n`;
  md += `Contributions are welcome! Please read our contributing guidelines first.\n\n`;

  // 5. Write to file
  try {
    fs.writeFileSync(outputPath, md);
    console.log(`Successfully generated ${OUTPUT_FILE} in ${rootDir}`);
  } catch (err) {
    console.error(`Failed to write ${OUTPUT_FILE}: ${err.message}`);
    process.exit(1);
  }
}

// Main Execution Logic
async function main() {
  const args = process.argv.slice(2);
  
  if (args.includes('--setup')) {
    await setupWrapper();
    return;
  }

  await generateReadme();
}

main().catch(err => {
  console.error(`Unhandled error: ${err.message}`);
  process.exit(1);
});