#!/usr/bin/env python3
"""
Resume & Cover Letter PDF Generator (v2.1)
Features:
  - Auto-detects Resume vs Cover Letter order and swaps them.
  - Fallback parser if 'markdown' library is missing.
  - Unified Header extraction.
  - --setup: Creates a shell wrapper 'resume-gen' in ~/bin.
"""

import os
import sys
import argparse
import re
import subprocess
from pathlib import Path

# Try to import markdown, but define a fallback if it fails
try:
    import markdown
    HAS_MARKDOWN = True
except ImportError:
    HAS_MARKDOWN = False
    print("⚠️  WARNING: 'markdown' library not found. Using built-in fallback parser.")
    print("   To fix: python3 -m pip install markdown")

try:
    from fpdf import FPDF
except ImportError:
    print("ERROR: Missing dependency: fpdf2")
    print("Install with: python3 -m pip install fpdf2")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

MARGIN_IN = 0.7
MARGIN_MM = MARGIN_IN * 25.4
PAGE_W_MM = 215.9
PAGE_H_MM = 279.4

FONT_NAME = "Cambria"
FONT_SIZE_BODY = 11
FONT_SIZE_HEADER = 12
FONT_SIZE_CONTACT = 10

# Font Paths
WORD_DFONT_BASE = "/Applications/Microsoft Word.app/Contents/Resources/DFonts"
CAMBRIA_FONTS = {
    "":   os.path.join(WORD_DFONT_BASE, "Cambria.ttc"),
    "B":  os.path.join(WORD_DFONT_BASE, "Cambriab.ttf"),
    "I":  os.path.join(WORD_DFONT_BASE, "Cambriai.ttf"),
    "BI": os.path.join(WORD_DFONT_BASE, "Cambriaz.ttf"),
}

TIMES_PATHS = [
    "/Library/Fonts/Times New Roman.ttf",
    os.path.expanduser("~/Library/Fonts/Times New Roman.ttf"),
    "C:/Windows/Fonts/times.ttf",
]

# Separators
MARKDOWN_SEPARATOR = "<!-- COVER LETTER START -->"
DOUBLE_DASH_SEPARATOR = "---\n---"

# ---------------------------------------------------------------------------
# Helper Functions
# ---------------------------------------------------------------------------

def find_font(paths):
    for p in paths:
        if os.path.exists(p):
            return p
    return None

def get_font_map():
    if all(os.path.exists(p) for p in CAMBRIA_FONTS.values()):
        return CAMBRIA_FONTS, FONT_NAME
    else:
        times = find_font(TIMES_PATHS)
        if times:
            return {"": times, "B": times, "I": times, "BI": times}, "TimesNewRoman"
        else:
            print("ERROR: Could not find Cambria or Times New Roman.")
            sys.exit(1)

def setup_wrapper():
    """
    Creates a shell wrapper script 'resume-gen' in ~/bin.
    The wrapper calls this script with all arguments passed to it.
    """
    # Get absolute path to THIS script
    script_path = os.path.abspath(__file__)
    
    # Determine target directory
    # You can change this to ~/.local/bin if you prefer
    bin_dir = os.path.expanduser("~/bin")
    wrapper_name = "resume-gen"
    wrapper_path = os.path.join(bin_dir, wrapper_name)
    
    # Ensure bin directory exists
    if not os.path.exists(bin_dir):
        os.makedirs(bin_dir)
        print(f"Created directory: {bin_dir}")
    
    # Remove existing file/link if present
    if os.path.islink(wrapper_path) or os.path.exists(wrapper_path):
        os.remove(wrapper_path)
        print(f"Removed existing: {wrapper_path}")
    
    # Create the shell wrapper content
    # We use $@ to pass all arguments
    wrapper_content = f"""#!/bin/zsh
# Wrapper for resume_gen.py
# Generated by resume_gen.py --setup

exec "{sys.executable}" "{script_path}" "$@"
"""
    
    # Write the wrapper
    with open(wrapper_path, 'w') as f:
        f.write(wrapper_content)
    
    # Make it executable
    os.chmod(wrapper_path, 0o755)
    
    print(f"✅ Wrapper created: {wrapper_path}")
    print(f"   Content: exec '{sys.executable}' '{script_path}' \"$@\"")
    print(f"   You can now run 'resume-gen <file.md>' from anywhere.")
    print(f"   Note: Ensure {bin_dir} is in your PATH.")
    
    # Check PATH
    current_path = os.environ.get('PATH', '')
    if bin_dir not in current_path:
        print(f"\n⚠️  WARNING: {bin_dir} is not in your PATH.")
        print(f"   Add this to your ~/.zshrc:")
        print(f"   export PATH=\"{bin_dir}:$PATH\"")
        print(f"   Then run: source ~/.zshrc")

# ---------------------------------------------------------------------------
# Document Processing Logic
# ---------------------------------------------------------------------------

def extract_header_info(text_block):
    """Extracts Name and Contact info from the top of a text block."""
    lines = text_block.strip().split('\n')
    name = ""
    contact_lines = []
    idx = 0
    
    while idx < len(lines) and not lines[idx].strip():
        idx += 1
    
    if idx >= len(lines):
        return "", [], text_block

    name = lines[idx].strip()
    idx += 1
    
    while idx < len(lines) and len(contact_lines) < 3:
        line = lines[idx].strip()
        if not line:
            idx += 1
            continue
        
        if '@' in line or '.' in line or '+' in line or '(' in line or len(line) < 80:
            if line.startswith('#'):
                break
            contact_lines.append(line)
        else:
            break
        idx += 1
        
    remaining = '\n'.join(lines[idx:])
    return name, contact_lines, remaining

def split_document(content):
    """Detects and splits Resume/Cover Letter, ensuring Cover Letter is first."""
    content = content.replace('\r\n', '\n')
    
    sep_idx = -1
    sep_type = None
    
    if MARKDOWN_SEPARATOR in content:
        sep_idx = content.find(MARKDOWN_SEPARATOR)
        sep_type = "MARKDOWN"
    elif DOUBLE_DASH_SEPARATOR in content:
        sep_idx = content.find(DOUBLE_DASH_SEPARATOR)
        sep_type = "DOUBLE_DASH"
    
    if sep_idx == -1:
        return content, "", "single"

    part1 = content[:sep_idx].strip()
    part2 = content[sep_idx + len(sep_type == "DOUBLE_DASH" and DOUBLE_DASH_SEPARATOR or MARKDOWN_SEPARATOR):].strip()
    
    p1_lower = part1.lower()
    p2_lower = part2.lower()
    
    is_p1_resume = any(k in p1_lower for k in ["experience", "skills", "education", "professional"])
    is_p1_letter = any(k in p1_lower for k in ["dear", "sincerely", "date", "cover letter"])
    is_p2_resume = any(k in p2_lower for k in ["experience", "skills", "education", "professional"])
    is_p2_letter = any(k in p2_lower for k in ["dear", "sincerely", "date", "cover letter"])
    
    cover_text = ""
    resume_text = ""
    
    if is_p1_letter and is_p2_resume:
        cover_text = part1
        resume_text = part2
    elif is_p1_resume and is_p2_letter:
        cover_text = part2
        resume_text = part1
    elif is_p1_letter and not is_p2_resume:
        cover_text = part1
        resume_text = part2
    elif is_p2_letter and not is_p1_resume:
        cover_text = part2
        resume_text = part1
    else:
        if is_p2_letter:
            cover_text = part2
            resume_text = part1
        else:
            cover_text = part1
            resume_text = part2

    return cover_text, resume_text, "split"

def parse_markdown_fallback(text):
    """Simple regex-based parser if 'markdown' lib is missing."""
    html = ""
    lines = text.split('\n')
    in_list = False
    
    for line in lines:
        stripped = line.strip()
        if not stripped:
            if in_list: html += "</ul>\n"; in_list = False
            html += "<p></p>"
            continue
        
        if stripped.startswith('### '):
            if in_list: html += "</ul>\n"; in_list = False
            html += f"<h3>{stripped[4:]}</h3>\n"
        elif stripped.startswith('## '):
            if in_list: html += "</ul>\n"; in_list = False
            html += f"<h2>{stripped[3:]}</h2>\n"
        elif stripped.startswith('# '):
            if in_list: html += "</ul>\n"; in_list = False
            html += f"<h1>{stripped[2:]}</h1>\n"
        elif stripped.startswith('**') and stripped.endswith('**'):
            html += f"<p><strong>{stripped[2:-2]}</strong></p>\n"
        elif stripped.startswith('- ') or stripped.startswith('* '):
            if not in_list:
                html += "<ul>\n"
                in_list = True
            txt = re.sub(r'^[-*]\s+', '', stripped)
            txt = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', txt)
            txt = re.sub(r'\*(.*?)\*', r'<em>\1</em>', txt)
            html += f"<li>{txt}</li>\n"
        else:
            if in_list:
                html += "</ul>\n"
                in_list = False
            txt = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', stripped)
            txt = re.sub(r'\*(.*?)\*', r'<em>\1</em>', txt)
            html += f"<p>{txt}</p>\n"
            
    if in_list:
        html += "</ul>\n"
    return html

def convert_to_html(text):
    if not text.strip():
        return ""
    if HAS_MARKDOWN:
        md = markdown.Markdown(extensions=['extra', 'codehilite'])
        return md.convert(text)
    else:
        return parse_markdown_fallback(text)

# ---------------------------------------------------------------------------
# PDF Builder
# ---------------------------------------------------------------------------

class ResumePDF(FPDF):
    def __init__(self, font_name):
        super().__init__(orientation="P", unit="mm", format="Letter")
        self.font_name = font_name
        self.set_margins(MARGIN_MM, MARGIN_MM, MARGIN_MM)
        self.set_auto_page_break(auto=True, margin=MARGIN_MM)
        
        font_map, _ = get_font_map()
        for style, path in font_map.items():
            self.add_font(font_name, style, path, uni=True)

    def draw_header(self, name, contact_lines):
        self.set_font(self.font_name, "B", 14)
        self.set_text_color(0, 0, 0)
        self.cell(0, 8, name, ln=True, align="C")
        
        self.set_font(self.font_name, "", FONT_SIZE_CONTACT)
        self.set_text_color(60, 60, 60)
        for line in contact_lines:
            self.cell(0, 5, line, ln=True, align="C")
        self.ln(4)

    def section_heading(self, text):
        self.ln(3)
        self.set_font(self.font_name, "B", FONT_SIZE_HEADER)
        self.set_text_color(0, 0, 0)
        self.cell(0, 6, text.upper(), ln=True)
        self.ln(1)

    def render_html(self, html_content):
        if not html_content:
            return
        html_content = html_content.replace('<br>', '\n').replace('<br/>', '\n')
        lines = html_content.split('\n')
        
        for line in lines:
            line = line.strip()
            if not line:
                continue
            
            if line.startswith('<h1>'):
                txt = re.sub(r'<[^>]+>', '', line)
                self.set_font(self.font_name, "B", 14)
                self.cell(0, 6, txt, ln=True)
                self.ln(2)
            elif line.startswith('<h2>'):
                txt = re.sub(r'<[^>]+>', '', line)
                self.section_heading(txt)
            elif line.startswith('<h3>'):
                txt = re.sub(r'<[^>]+>', '', line)
                self.set_font(self.font_name, "B", 11)
                self.cell(0, 5, txt, ln=True)
                self.ln(1)
            elif line.startswith('<hr'):
                self.line(self.x, self.y, self.w - self.r_margin, self.y)
                self.ln(2)
            elif line.startswith('<li>'):
                txt = re.sub(r'<[^>]+>', '', line)
                self.set_font(self.font_name, "", FONT_SIZE_BODY)
                self.set_text_color(0, 0, 0)
                bullet = "\u2022"
                bw = self.get_string_width(bullet + " ")
                self.cell(bw, 5, bullet, ln=False)
                self.multi_cell(self.w - self.l_margin - self.r_margin - bw, 5, txt, ln=True)
            elif line.startswith('<p>') or line.startswith('<div>'):
                txt = re.sub(r'<[^>]+>', '', line)
                if txt:
                    self.set_font(self.font_name, "", FONT_SIZE_BODY)
                    self.set_text_color(0, 0, 0)
                    self.multi_cell(self.w - self.l_margin - self.r_margin, 5, txt, ln=True)
            else:
                if line:
                    self.set_font(self.font_name, "", FONT_SIZE_BODY)
                    self.set_text_color(0, 0, 0)
                    self.multi_cell(self.w - self.l_margin - self.r_margin, 5, line, ln=True)

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Generate Resume/Cover Letter PDF")
    parser.add_argument('input_file', nargs='?', help="Path to markdown file")
    parser.add_argument('--setup', action='store_true', help="Create shell wrapper 'resume-gen'")
    parser.add_argument('-o', '--output', help="Output filename")
    
    args = parser.parse_args()

    if args.setup:
        setup_wrapper()
        return

    if not args.input_file:
        print("Error: No input file specified.")
        print("Usage: resume-gen <file.md> [--setup]")
        sys.exit(1)

    if not os.path.exists(args.input_file):
        print(f"Error: File not found: {args.input_file}")
        sys.exit(1)

    with open(args.input_file, 'r', encoding='utf-8') as f:
        content = f.read()

    cover_raw, resume_raw, mode = split_document(content)
    primary_text = cover_raw if cover_raw else resume_raw
    name, contact_lines, _ = extract_header_info(primary_text)
    
    if not name:
        print("Error: Could not detect Name/Contact info.")
        sys.exit(1)

    cover_html = convert_to_html(cover_raw) if cover_raw else ""
    resume_html = convert_to_html(resume_raw) if resume_raw else ""

    if args.output:
        output_path = args.output
    else:
        base = os.path.splitext(os.path.basename(args.input_file))[0]
        output_path = f"{base}.pdf"

    pdf = ResumePDF(FONT_NAME)
    pdf.add_page()
    
    if cover_html:
        pdf.draw_header(name, contact_lines)
        pdf.render_html(cover_html)
        if resume_html:
            pdf.add_page()
            pdf.draw_header(name, contact_lines)
            pdf.render_html(resume_html)
    else:
        pdf.draw_header(name, contact_lines)
        pdf.render_html(resume_html)

    pdf.output(output_path)
    print(f"✅ Generated: {output_path} ({pdf.page} pages)")
    if mode == "split":
        print("   Detected: Cover Letter + Resume (Reordered)")
    else:
        print("   Detected: Single Document")

if __name__ == "__main__":
    main()